### ISSUE TITLE
Undocumented chart in helm repo

### ISSUE THREAD

**Issue by brianclemens** [woodpecker-ci/helm#45]
There appears to be a chart with an older chart version (but newer Woodpecker version?) in the repo. Probably best to remove it to avoid confusion.

<img width="971" alt="image" src="https://github.com/woodpecker-ci/helm/assets/13581364/f1fe5e46-de58-4726-aeff-878284b98e06">

**Comment by pat-s** [comment]
0.1.5 is the most recent chart and WP 0.15.9 the most recent "release".

The older versions with chart version "0.15.6" didn't properly distinguish between chart and app version.

**Comment by Rojikku** [comment]
I did, in fact, notice the lack of proper distinguishment when I spent the last two hours trying to deploy woodpecker.

https://woodpecker-ci.org/docs/administration/kubernetes

But why, might I ask, *weren't the docs updated*?
Why would you do a breaking change and not update the docs?!

I'm going to try switching to the root chart from the individual agent and server charts, because the agent chart appears to be addicted to `dind` containers and refuses to just not deploy them like I ask and the settings are set to.

**Comment by 6543** [comment]
the helm charts did got split out from the main repo and so they had new tagging ... we have to remove the old refs now ...

**Comment by 6543** [comment]
... but I'm not sure if this is kind a breaking etc ...

**Comment by Rojikku** [comment]
> the helm charts did got split out from the main repo and so they had new tagging ... we have to remove the old refs now ...

Ah, is that what happened? That makes more sense.

**Comment by pat-s** [comment]
@6543 Given how new the k8s support is and that it only really works in next, I guess removing the old releases would be fine here. Would also clear confusion...
I don't think there are many users atm and even if, they should be on 0.1.5 by now or be "forced" to migrate.

If a "fresh start" would help, now would be a good time I guess.

I can check if permissions allow me to do so but feel free to go ahead yourself.
I won't do it until either you or @anbraten confirm this action.

**Comment by anbraten** [comment]
@pat-s give it a try. otherwise feel free to tag me, so I can have a look

**Comment by pat-s** [comment]
@anbraten Can't do it, no access to https://github.com/woodpecker-ci/woodpecker-ci.github.io

**Comment by anbraten** [comment]
How can I remove it. Should I just remove the lines of woodpecker-server & woodpecker-agent from the index.yaml?

**Comment by pat-s** [comment]
Yes remove them from the index.yaml and maybe also delete the GH releases and assets

**Comment by anbraten** [comment]
removed the old charts from the index.

**Comment by Rojikku** [comment]
@anbraten You uh, tested this right? Because I'm getting a *lot* of angry error messages from my helm bot right now about woodpecker.
I'll go on in a minute and see if maybe deleting and re-adding to clear a cache or something helps... But since I've never had this happen before I assume something has gone wrong.
